<?php
$f = 'resources/views/layouts/app.blade.php';
$c = file_get_contents($f);

$start = strpos($c, "/* ========================================\n           LIGHT THEME");
$end = strpos($c, "</style>", $start);

$newCss  = "/* ========================================\n";
$newCss .= "           LIGHT THEME - Dark \"Golden Desert\"\n";
$newCss .= "           Warm, rich, high contrast\n";
$newCss .= "           ======================================== */\n";

$newCss .= "        .light-theme body { background: #b8ac98 !important; color: #14110c !important; }\n";
$newCss .= "        .light-theme .content-area { color: #14110c !important; }\n";
$newCss .= "        .light-theme .content-area > header { background: rgba(184,172,152,0.92) !important; backdrop-filter: blur(20px) !important; border-bottom: 1px solid #8a7d6e !important; }\n";
$newCss .= "        .light-theme .content-area > header button, .light-theme .content-area > header a { color: #4a453c !important; }\n";
$newCss .= "        .light-theme .content-area > header button:hover, .light-theme .content-area > header a:hover { color: #5a3f10 !important; }\n";
$newCss .= "        .light-theme .bg-navy, .light-theme .bg-\\[#111B2E\\] { background: #c8bcac !important; border: 1px solid #8a7d6e !important; box-shadow: 0 1px 3px rgba(30,20,10,0.15), 0 4px 16px rgba(30,20,10,0.08) !important; }\n";
$newCss .= "        .light-theme .card-premium { background: #c8bcac !important; border: 1px solid #8a7d6e !important; }\n";
$newCss .= "        .light-theme .stat-card { background: #c8bcac !important; border: 1px solid #8a7d6e !important; }\n";
$newCss .= "        .light-theme .stat-card:hover { background: #beb2a0 !important; border-color: rgba(90,63,16,0.50) !important; }\n";
$newCss .= "        .light-theme .content-area input, .light-theme .content-area textarea, .light-theme .content-area select { background: #beb2a0 !important; color: #14110c !important; border-color: #8a7d6e !important; }\n";
$newCss .= "        .light-theme .content-area input:focus, .light-theme .content-area textarea:focus, .light-theme .content-area select:focus { border-color: #5a3f10 !important; box-shadow: 0 0 0 3px rgba(90,63,16,0.25) !important; }\n";
$newCss .= "        .light-theme .content-area input::placeholder, .light-theme .content-area textarea::placeholder { color: #6b6558 !important; }\n";
$newCss .= "        .light-theme .content-area select option { background: #c8bcac !important; color: #14110c !important; }\n";
$newCss .= "        .light-theme .content-area .text-white { color: #14110c !important; }\n";
$newCss .= "        .light-theme .content-area .text-white\\/80 { color: #22201a !important; }\n";
$newCss .= "        .light-theme .content-area .text-white\\/70 { color: #2e2a22 !important; }\n";
$newCss .= "        .light-theme .content-area .text-white\\/60 { color: #3d3830 !important; }\n";
$newCss .= "        .light-theme .content-area .text-white\\/50 { color: #4a453c !important; }\n";
$newCss .= "        .light-theme .content-area .text-white\\/40 { color: #5a5448 !important; }\n";
$newCss .= "        .light-theme .content-area .text-white\\/30 { color: #6b6558 !important; }\n";
$newCss .= "        .light-theme .content-area .text-white\\/20 { color: #7a7568 !important; }\n";
$newCss .= "        .light-theme .content-area .bg-gray-50 { background: #b8ac98 !important; }\n";
$newCss .= "        .light-theme .content-area .bg-gray-100 { background: #b0a494 !important; }\n";
$newCss .= "        .light-theme .content-area .border-white\\/10, .light-theme .content-area .border-white\\/15, .light-theme .content-area .border-white\\/20 { border-color: #8a7d6e !important; }\n";
$newCss .= "        .light-theme .content-area .border-white\\/5 { border-color: #a89b8c !important; }\n";
$newCss .= "        .light-theme .content-area .bg-white\\/5 { background: #beb2a0 !important; }\n";
$newCss .= "        .light-theme .content-area .bg-white\\/[0.03] { background: #b8ac98 !important; }\n";
$newCss .= "        .light-theme .content-area .bg-white\\/[0.04] { background: #b8ac98 !important; }\n";
$newCss .= "        .light-theme .content-area .bg-navy-lighter { background: #b8ac98 !important; }\n";
$newCss .= "        .light-theme .content-area .bg-navy-light { background: #c8bcac !important; }\n";
$newCss .= "        .light-theme .content-area .bg-ivory\\/10 { background: rgba(80,60,40,0.15) !important; }\n";
$newCss .= "        .light-theme .content-area .hover\\:bg-navy-lighter\\/50:hover { background: #b0a494 !important; }\n";
$newCss .= "        .light-theme .content-area .hover\\:bg-white\\/10:hover { background: #b8ac98 !important; }\n";
$newCss .= "        .light-theme .content-area .hover\\:bg-[#0f2240]:hover { background: #b8ac98 !important; }\n";
$newCss .= "        .light-theme .content-area .hover\\:text-white:hover { color: #14110c !important; }\n";
$newCss .= "        .light-theme .content-area table { color: #14110c !important; }\n";
$newCss .= "        .light-theme .content-area thead th { color: #3d3830 !important; border-bottom-color: #8a7d6e !important; background: #b8ac98 !important; }\n";
$newCss .= "        .light-theme .content-area tbody td { border-bottom-color: #a89b8c !important; color: #14110c !important; }\n";
$newCss .= "        .light-theme .content-area tbody tr:hover td { background: #beb2a0 !important; }\n";
$newCss .= "        .light-theme .content-area .divide-y.divide-white\\/5 > *, .light-theme .content-area .divide-y.divide-ivory\\/5 > * { border-color: #a89b8c !important; }\n";
$newCss .= "        .light-theme .content-area .text-green-400 { color: #0a4522 !important; }\n";
$newCss .= "        .light-theme .content-area .text-yellow-400 { color: #5a420a !important; }\n";
$newCss .= "        .light-theme .content-area .text-red-400 { color: #7a1010 !important; }\n";
$newCss .= "        .light-theme .content-area .text-blue-400 { color: #152d60 !important; }\n";
$newCss .= "        .light-theme .content-area .text-gold { color: #4a3510 !important; }\n";
$newCss .= "        .light-theme .content-area label { color: #2e2a22 !important; }\n";
$newCss .= "        .light-theme .btn-ghost { background: rgba(80,60,40,0.15) !important; color: #2e2a22 !important; }\n";
$newCss .= "        .light-theme .btn-ghost:hover { background: rgba(80,60,40,0.22) !important; color: #14110c !important; }\n";
$newCss .= "        .light-theme .dropdown-dark { background: #c8bcac !important; border: 1px solid #8a7d6e !important; box-shadow: 0 10px 30px rgba(30,20,10,0.18) !important; }\n";
$newCss .= "        .light-theme .dropdown-dark h3, .light-theme .dropdown-dark a p, .light-theme .dropdown-dark span { color: #14110c !important; }\n";
$newCss .= "        .light-theme .dropdown-dark a { color: #2e2a22 !important; }\n";
$newCss .= "        .light-theme .dropdown-dark a:hover { background: #b8ac98 !important; }\n";
$newCss .= "        .light-theme .content-area nav a { background: #c8bcac !important; color: #2e2a22 !important; border: 1px solid #8a7d6e !important; }\n";
$newCss .= "        .light-theme .content-area nav a:hover { border-color: #5a3f10 !important; color: #5a3f10 !important; }\n";
$newCss .= "        .light-theme .content-area .bg-[#C9A55A] { background: #5a3f10 !important; color: #f5f0e8 !important; }\n";
$newCss .= "        .light-theme ::-webkit-scrollbar-track { background: #b8ac98; }\n";
$newCss .= "        .light-theme ::-webkit-scrollbar-thumb { background: #7a6d5e; }\n";
$newCss .= "        .light-theme input[type=checkbox] { accent-color: #5a3f10 !important; }\n";
$newCss .= "        .light-theme .bg-red-500\\/10 { background: rgba(239,68,68,0.10) !important; }\n";
$newCss .= "        .light-theme .border-\\[#C9A55A\\]\\/20 { border-color: rgba(90,63,16,0.35) !important; }\n";
$newCss .= "        .light-theme aside[style*=linear-gradient] { background: linear-gradient(180deg, #1a2038, #0f1428) !important; }\n";
$newCss .= "        .light-theme aside .text-white\\/50 { color: rgba(255,255,255,.55) !important; }\n";
$newCss .= "        .light-theme aside .text-white\\/20 { color: rgba(255,255,255,.25) !important; }\n";
$newCss .= "        .light-theme aside .sidebar-link:hover { background: rgba(201,165,90,.12) !important; }\n";

$c = substr_replace($c, $newCss, $start, $end - $start);
file_put_contents($f, $c);
echo "Done!";
